version: '3'

services:
  db:
    image: 'postgis/postgis:11-2.5-alpine'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always             # run as a service

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    build: .
    command: bundle exec sidekiq -C ./config/scheduler.yml
    environment:
      - JOB_WORKER_URL=redis://redis:6379/0
      - DATABASE_HOST=db
    depends_on:
      - 'redis'
      - 'db'

  web:
    depends_on:
      - 'db'
      - 'redis'
      - 'sidekiq'
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./reports:/project/reports

volumes:
  redis:
  postgres:
